version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/London"

    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

    groups:
      routine-minor-and-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
